return {
	remasteredBalance = false,
	enable_remastered_balance = true,
	enable_admin_balance_tests = true,
	remasteredEvents = false,
	talentSystem = false,
	challengeSystem = false,
	newBosses = false,
	interfaceImprovements = false,
	networkExtensions = false,
	debugCommands = false,
	enable_upstream_pack_01 = false,
	enable_upstream_pack_01_items = false,
	enable_upstream_pack_01_monsters = false,
	enable_upstream_pack_01_npcs = false,
	enable_upstream_pack_01_quests = false,
	enable_upstream_pack_01_maps = false,
	exampleModule = true,
	disabledExampleModule = false,
	invalidExampleModule = false,
	missingDependencyExampleModule = true,
}
